name: Draft-New
favicon: null
layout_spectrum: 0.4996041222475469
typography_spectrum: 0.9797130867373198
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.23321210406720638
  lightness: 0.8668602975085378
  saturation: 0.4022235535085201
  rhythmicContrast: 0.2953675566241145
purpose: []
